spring:
  application:
    name: project

  datasource:
    url: {SPRING_DATASOURCE_URL}

  jwt:
    secret: ${JWT_SECRET}
    accessTokenExpiration: 7200  # 2h
    refreshTokenExpiration: 604800  # 7d

websiteUrl: https://mystore.com