spring:
  application:
    name: project

  datasource:
    url: jdbc:postgresql://localhost:5432/mydb
    username: mahmoud
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: org.postgresql.Driver

  flyway:
    enabled: true
    locations: classpath:db/migration

  jpa:
    hibernate:
      ddl-auto: none

    properties:
      hibernate:
        default_schema: practice_schema

    show-sql: true

  jwt:
    secret: ${JWT_SECRET}
    accessTokenExpiration: 7200  # 2h
    refreshTokenExpiration: 604800  # 7d

  jackson:
    mapper:
      sort-properties-alphabetically: false

stripe:
  secretKey: ${STRIPE_SECRET_KEY}
  webhookSecretKey: ${STRIPE_WEBHOOK_SECRET_KEY}

websiteUrl: http://localhost:3000